FROM rust AS builder

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y musl-tools && \
    rustup target add x86_64-unknown-linux-musl


RUN cargo build --release --target x86_64-unknown-linux-musl

# Etap 2: Runtime - stabilny Debian
FROM alpine:latest

COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/flexnotes .

# Add run permission
RUN chmod +x ./flexnotes

CMD ["./flexnotes"]

